import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

interface TestResult {
  score: number;
  total: number;
  accuracy: number;
  exam: string;
  createdAt: string;
  topicBreakdown?: Record<string, { correct: number; total: number }>;
  weakTopics?: string[];
}

export function exportTestResultToPDF(result: TestResult) {
  const doc = new jsPDF();
  
  // Title
  doc.setFontSize(20);
  doc.text("Test Results Report", 14, 20);
  
  // Exam info
  doc.setFontSize(12);
  doc.text(`Exam: ${result.exam}`, 14, 30);
  doc.text(`Date: ${new Date(result.createdAt).toLocaleDateString()}`, 14, 36);
  
  // Overall score
  doc.setFontSize(16);
  doc.text("Overall Performance", 14, 48);
  doc.setFontSize(12);
  doc.text(`Score: ${result.score}/${result.total}`, 14, 56);
  doc.text(`Accuracy: ${result.accuracy.toFixed(1)}%`, 14, 62);
  
  // Topic breakdown table
  if (result.topicBreakdown && Object.keys(result.topicBreakdown).length > 0) {
    doc.setFontSize(16);
    doc.text("Topic-wise Performance", 14, 74);
    
    const tableData = Object.entries(result.topicBreakdown).map(([topic, stats]) => {
      const topicAccuracy = (stats.correct / stats.total) * 100;
      return [
        topic,
        `${stats.correct}/${stats.total}`,
        `${topicAccuracy.toFixed(1)}%`,
      ];
    });
    
    autoTable(doc, {
      startY: 80,
      head: [["Topic", "Score", "Accuracy"]],
      body: tableData,
      theme: "striped",
      headStyles: { fillColor: [59, 130, 246] },
    });
  }
  
  // Weak topics
  if (result.weakTopics && result.weakTopics.length > 0) {
    const finalY = (doc as any).lastAutoTable.finalY || 100;
    doc.setFontSize(16);
    doc.text("Areas to Improve", 14, finalY + 10);
    doc.setFontSize(12);
    doc.text(result.weakTopics.join(", "), 14, finalY + 18, {
      maxWidth: 180,
    });
  }
  
  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(10);
    doc.text(
      `Page ${i} of ${pageCount} - Generated by CrackGov.ai`,
      105,
      doc.internal.pageSize.height - 10,
      { align: "center" }
    );
  }
  
  // Save
  doc.save(`test-result-${result.exam}-${new Date(result.createdAt).toISOString().split("T")[0]}.pdf`);
}

