/**
 * Development Environment Setup Script
 * Creates/updates .env file with all required variables for development
 * Run with: node scripts/setup-dev-env.js
 */

const fs = require('fs');
const crypto = require('crypto');
const path = require('path');

const envPath = path.join(__dirname, '..', '.env');
const envExamplePath = path.join(__dirname, '..', '.env.example');

// Generate secure keys
const nextAuthSecret = crypto.randomBytes(32).toString('base64');
const encryptionKey = crypto.randomBytes(32).toString('base64');

// Development environment template
const devEnvTemplate = `# ============================================
# CrackGov.ai - Development Environment
# ============================================
# Auto-generated by setup-dev-env.js
# DO NOT commit this file to version control

# ============================================
# REQUIRED - Core Configuration
# ============================================

# Database Configuration
# For local development with Docker Compose:
DATABASE_URL="postgresql://crackgov:password@localhost:5432/crackgov"
# For local PostgreSQL installation, use:
# DATABASE_URL="postgresql://postgres:yourpassword@localhost:5432/crackgov"

# Database Read Replica (Optional - for production)
# DATABASE_READ_REPLICA_URL="postgresql://user:pass@replica:5432/crackgov"

# Redis Configuration
# For local development with Docker Compose:
REDIS_URL="redis://localhost:6379"
# For local Redis installation, use:
# REDIS_URL="redis://localhost:6379"
# For Redis Cloud or other managed services:
# REDIS_URL="rediss://username:password@host:port"

# Authentication Configuration
NEXTAUTH_URL="http://localhost:3000"
NEXTAUTH_SECRET="${nextAuthSecret}"

# Encryption Key (32-byte base64 encoded)
# Used for encrypting API keys and sensitive data
ENCRYPTION_KEY="${encryptionKey}"

# ============================================
# OPTIONAL - AI Configuration
# ============================================

# OpenAI API Key (Legacy - now managed via Admin Panel)
# OPENAI_API_KEY="sk-your-openai-api-key-here"

# Gemini API Key (Fallback - used if all database keys fail)
# Get API key from https://makersuite.google.com/app/apikey
# GEMINI_API_KEY="your-gemini-api-key-here"
# OR
# GOOGLE_GEMINI_API_KEY="your-gemini-api-key-here"

# ============================================
# OPTIONAL - Monitoring & Error Tracking
# ============================================

# Sentry Error Tracking (Optional)
# Get your DSN from https://sentry.io
# NEXT_PUBLIC_SENTRY_DSN="https://xxx@sentry.io/xxx"
# SENTRY_DSN="https://xxx@sentry.io/xxx"

# ============================================
# OPTIONAL - Email Service
# ============================================

# Choose ONE email service provider:

# Option 1: Resend (Recommended - Free tier: 3,000 emails/month)
# Get API key from https://resend.com
# RESEND_API_KEY="re_xxx"

# Option 2: SendGrid (Free tier: 100 emails/day)
# Get API key from https://sendgrid.com
# SENDGRID_API_KEY="SG.xxx"

# ============================================
# OPTIONAL - File Storage
# ============================================

# Storage Provider: "s3", "r2", or "local" (default: "local" for dev)
STORAGE_PROVIDER="local"

# Option 1: AWS S3
# AWS_ACCESS_KEY_ID="your-aws-access-key-id"
# AWS_SECRET_ACCESS_KEY="your-aws-secret-access-key"
# AWS_S3_BUCKET="your-bucket-name"
# AWS_REGION="ap-south-1"
# STORAGE_PUBLIC_URL="https://your-bucket.s3.ap-south-1.amazonaws.com"

# Option 2: Cloudflare R2 (S3-compatible)
# R2_BUCKET="your-r2-bucket-name"
# R2_ENDPOINT="https://your-account-id.r2.cloudflarestorage.com"
# AWS_ACCESS_KEY_ID="your-r2-access-key-id"
# AWS_SECRET_ACCESS_KEY="your-r2-secret-access-key"
# STORAGE_PROVIDER="r2"
# STORAGE_PUBLIC_URL="https://your-domain.com"

# ============================================
# OPTIONAL - Payment Gateway
# ============================================

# Razorpay Configuration (Optional - can be configured via Admin Panel)
# Get credentials from https://razorpay.com
# RAZORPAY_KEY_ID="rzp_test_xxx"
# RAZORPAY_KEY_SECRET="your-razorpay-secret"

# ============================================
# OPTIONAL - Security
# ============================================

# CSRF Secret (defaults to NEXTAUTH_SECRET if not set)
# CSRF_SECRET="your-csrf-secret-here"

# ============================================
# OPTIONAL - Development Settings
# ============================================

# Node Environment
NODE_ENV="development"

# Disable Redis (for testing without Redis)
# DISABLE_REDIS="true"
`;

// Check if .env already exists
if (fs.existsSync(envPath)) {
  console.log('⚠️  .env file already exists!');
  console.log('   The file will be backed up to .env.backup');
  
  // Create backup
  const backupPath = envPath + '.backup';
  fs.copyFileSync(envPath, backupPath);
  console.log(`   Backup created: .env.backup`);
  
  // Read existing file
  const existingContent = fs.readFileSync(envPath, 'utf8');
  
  // Only update if keys are placeholders
  let updatedContent = existingContent;
  
  if (existingContent.includes('your-nextauth-secret') || 
      existingContent.includes('your-secret-key-here') ||
      !existingContent.includes('NEXTAUTH_SECRET=')) {
    updatedContent = updatedContent.replace(
      /NEXTAUTH_SECRET=.*/g,
      `NEXTAUTH_SECRET="${nextAuthSecret}"`
    );
    if (!updatedContent.includes('NEXTAUTH_SECRET=')) {
      updatedContent = `NEXTAUTH_SECRET="${nextAuthSecret}"\n${updatedContent}`;
    }
    console.log('✅ Updated NEXTAUTH_SECRET');
  }
  
  if (existingContent.includes('your-32-byte-encryption-key') || 
      existingContent.includes('your-encryption-key') ||
      !existingContent.includes('ENCRYPTION_KEY=')) {
    updatedContent = updatedContent.replace(
      /ENCRYPTION_KEY=.*/g,
      `ENCRYPTION_KEY="${encryptionKey}"`
    );
    if (!updatedContent.includes('ENCRYPTION_KEY=')) {
      updatedContent = `ENCRYPTION_KEY="${encryptionKey}"\n${updatedContent}`;
    }
    console.log('✅ Updated ENCRYPTION_KEY');
  }
  
  // Ensure required variables exist
  if (!updatedContent.includes('DATABASE_URL=')) {
    updatedContent = `DATABASE_URL="postgresql://crackgov:password@localhost:5432/crackgov"\n${updatedContent}`;
    console.log('✅ Added DATABASE_URL');
  }
  
  if (!updatedContent.includes('REDIS_URL=')) {
    updatedContent = `REDIS_URL="redis://localhost:6379"\n${updatedContent}`;
    console.log('✅ Added REDIS_URL');
  }
  
  if (!updatedContent.includes('NEXTAUTH_URL=')) {
    updatedContent = `NEXTAUTH_URL="http://localhost:3000"\n${updatedContent}`;
    console.log('✅ Added NEXTAUTH_URL');
  }
  
  fs.writeFileSync(envPath, updatedContent, 'utf8');
} else {
  // Create new .env file
  fs.writeFileSync(envPath, devEnvTemplate, 'utf8');
  console.log('✅ Created new .env file');
}

console.log('\n✅ Development environment setup complete!');
console.log('\n📝 Generated secure keys:');
console.log(`   NEXTAUTH_SECRET: ${nextAuthSecret}`);
console.log(`   ENCRYPTION_KEY: ${encryptionKey}`);
console.log('\n📋 Next steps:');
console.log('   1. Review and update .env file with your actual credentials');
console.log('   2. Start PostgreSQL and Redis (or use docker-compose up -d)');
console.log('   3. Run: npm run dev');
console.log('   4. Start workers: npm run workers (in separate terminal)');
console.log('\n⚠️  Keep your .env file secure and never commit it to version control!');

